name: Sonar Cube Coverage
on:
  push:
    branches:
      - master
      - main
      - dev
      - qa
      - feature/sonar-cube-setup
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: "16.x" # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  sonarcloud:
    environment: DEV
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: ".env"
          fileDir: "./"
          encodedString: ${{ secrets.ALL }}

      - name: Install dependencies
        run: npm ci
      - name: Run build and test
        run: npm run build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
